# Generated by Django 5.2.11 on 2026-02-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20190522_1236'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='send_to_email',
            field=models.BooleanField(default=True, verbose_name='Отправить в сообщении'),
        ),
        migrations.AddField(
            model_name='form',
            name='email_message_copies',
            field=models.TextField(blank=True, verbose_name='Сообщение для копий'),
        ),
        migrations.AddField(
            model_name='form',
            name='email_subject_copies',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тема для копий'),
        ),
        migrations.AddField(
            model_name='form',
            name='send_to_crm',
            field=models.BooleanField(default=False, verbose_name='Отправить в CRM'),
        ),
        migrations.AddField(
            model_name='form',
            name='show_required_block',
            field=models.BooleanField(default=True, verbose_name='Показать блок "Необходимо заполнить поля"'),
        ),
        migrations.AddField(
            model_name='form',
            name='tipe_in_crm',
            field=models.PositiveSmallIntegerField(choices=[(0, 'заявка с сайта'), (1, 'заявка на франчайзинг'), (2, 'подписка франчайзинг'), (3, 'туршкола')], default=0, help_text='Актуально только при включённом "Отправить в CRM"', verbose_name='Тип данных в CRM'),
        ),
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Help text'),
        ),
        migrations.AlterField(
            model_name='field',
            name='placeholder_text',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Placeholder Text'),
        ),
        migrations.AlterField(
            model_name='form',
            name='sites',
            field=models.ManyToManyField(default=[1], related_name='%(app_label)s_%(class)s_forms', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
